apiVersion: apps/v1
kind: Deployment
metadata:
  name: ice-cream-api
  labels:
    app: ice-cream-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ice-cream-api
  template:
    metadata:
      labels:
        app: ice-cream-api
    spec:
      containers:
        - name: train-register-deploy-model
          image: sajagmathur/icecream-api
          command: ["python"]
          args: ["app.py"]
          ports:
            - containerPort: 5001
          imagePullPolicy: IfNotPresent
