apiVersion: v1
kind: Service
metadata:
  name: ice-cream-service
spec:
  selector:
    app: icecream-api  # Ensure this matches the label in the Deployment
  ports:
    - protocol: TCP
      port: 80         # Exposed port outside the cluster
      targetPort: 8000  # The port the app is actually listening on inside the container
  type: LoadBalancer   # This makes it accessible externally (use NodePort for internal access only)
