apiVersion: v1
kind: Service
metadata:
  name: ice-cream-service
spec:
  type: NodePort
  selector:
    app: ice-cream-api
  ports:
    - protocol: TCP
      port: 5001         # Service port inside the cluster
      targetPort: 5001   # Port your container listens on
      nodePort: 32001    # External port exposed on node (must be 30000-32767)
      # You can change nodePort to any available port in the range 30000-32767
