apiVersion: v1
kind: Service
metadata:
  name: ice-cream-service
spec:
  selector:
    app: icecream-api
  ports:
    - protocol: TCP
      port: 80         # Exposed port outside the cluster
      targetPort: 8000  # The port inside the container
      nodePort: 31244   # Port available on the node
  type: NodePort      # Change to NodePort for local setups
