name: Debug Kubernetes Connectivity

on:
  workflow_dispatch:  # manually trigger

jobs:
  kubectl-connectivity-check:
    runs-on: self-hosted  # make sure this matches your runner label

    steps:
      - name: Show current user
        run: whoami

      - name: List .kube directory contents
        run: ls -la ~/.kube || echo ".kube directory does not exist"

      - name: Show kubeconfig content
        run: cat ~/.kube/config || echo "No kubeconfig file found"

      - name: Create .kube directory if missing
        run: mkdir -p ~/.kube

      - name: Setup kubeconfig from secret
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Show kubeconfig file after write
        run: cat ~/.kube/config

      - name: Check kubectl version
        run: kubectl version --client

      - name: Get Kubernetes nodes
        run: kubectl get nodes

      - name: Get pods in all namespaces
        run: kubectl get pods --all-namespaces
