name: Debug Kubernetes Connectivity

on:
  workflow_dispatch:  # manually trigger

jobs:
  kubectl-connectivity-check:
    runs-on: self-hosted  # make sure this matches your runner label

    steps:
      - name: Show current user
        shell: powershell
        run: whoami

      - name: List .kube directory contents
        shell: powershell
        run: |
          if (Test-Path "$HOME\.kube") {
            Get-ChildItem "$HOME\.kube" -Force
          } else {
            Write-Output ".kube directory does not exist"
          }

      - name: Show kubeconfig content
        shell: powershell
        run: |
          if (Test-Path "$HOME\.kube\config") {
            Get-Content "$HOME\.kube\config"
          } else {
            Write-Output "No kubeconfig file found"
          }

      - name: Create .kube directory if missing
        shell: powershell
        run: |
          if (-not (Test-Path "$HOME\.kube")) {
            New-Item -ItemType Directory -Path "$HOME\.kube" | Out-Null
          }

      - name: Setup kubeconfig from secret
        shell: powershell
        run: |
          $kubeconfigData = "${{ secrets.KUBECONFIG_DATA }}"
          $kubeconfigPath = "$HOME\.kube\config"
          $kubeconfigData | Out-File -FilePath $kubeconfigPath -Encoding ascii
          icacls $kubeconfigPath /inheritance:r /grant:r "$env:USERNAME:(R)"

      - name: Show kubeconfig file after write
        shell: powershell
        run: Get-Content "$HOME\.kube\config"

      - name: Check kubectl version
        shell: powershell
        run: kubectl version --client

      - name: Get Kubernetes nodes
        shell: powershell
        run: kubectl get nodes

      - name: Get pods in all namespaces
        shell: powershell
        run: kubectl get pods --all-namespaces
