name: Train and Register Model

on:
  push:
    branches: [Day10]

jobs:
  train-model:
    runs-on: IceCream  # Your self-hosted runner label

    steps:
      - uses: actions/checkout@v3

      - name: Create python environment
        shell: powershell
        run: |
          $cacheDir = "$env:USERPROFILE\actions-cache"
          if (-not (Test-Path $cacheDir)) {
            New-Item -ItemType Directory -Path $cacheDir | Out-Null
          }
          python -m venv "$cacheDir\env"

      - name: Train and log to MLflow
        shell: powershell
        run: |
          $cacheDir = "$env:USERPROFILE\actions-cache"
          # Activate virtual environment
          & "$cacheDir\env\Scripts\Activate.ps1"
          pip install --quiet mlflow
          Set-Location -Path Day10/workshop
          python register.py
