name: Train and Register Model

on:
  push:
    branches: [Day10]

jobs:
  train-model:
    runs-on: IceCream

    steps:
      - uses: actions/checkout@v3

      - name: Create python environment
        shell: bash  # ✅ Force bash
        run: |
          CACHE_DIR="$HOME/actions-cache"
          mkdir -p "$CACHE_DIR"
          python -m venv "$CACHE_DIR/env"

      - name: Train and log to MLflow
        shell: bash  # ✅ Force bash
        run: |
          CACHE_DIR="$HOME/actions-cache"
          source "$CACHE_DIR/env/bin/activate"
          pip install mlflow
          cd Day10/workshop
          python register.py
