name: Train, Register, and Deploy Model

on:
  push:
    branches: [Day10]

jobs:
  train-model:
    runs-on: IceCream
    steps:
      - uses: actions/checkout@v3
      # ... (your existing steps unchanged)

  register-model:
    runs-on: IceCream
    needs: train-model
    steps:
      - uses: actions/checkout@v3
      # ... (your existing steps unchanged)

  dockerize-model:
    runs-on: IceCream
    needs: register-model
    steps:
      - uses: actions/checkout@v3

      - name: Stop and remove existing container if it exists
        shell: powershell
        run: |
          $containerName = "icecream-api"
          docker stop $containerName 2>$null
          docker rm $containerName 2>$null

      - name: Build Docker image locally
        shell: powershell
        run: |
          $imageName = "icecream-api:latest"
          docker build -t $imageName Day10/workshop

      - name: Run Docker container locally
        shell: powershell
        run: |
          $containerName = "icecream-api"
          docker run -d --name $containerName -p 5001:5001 icecream-api:latest

      - name: Confirm container is running
        shell: powershell
        run: |
          docker ps -f "name=icecream-api"

  launch-app:
    runs-on: IceCream
    needs: dockerize-model
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python environment
        shell: powershell
        run: |
          $envPath = "$env:USERPROFILE\actions-cache\env"
          if (-not (Test-Path $envPath)) {
            python -m venv $envPath
          }
          & "$envPath\Scripts\Activate.ps1"
          pip install fastapi uvicorn numpy

      - name: Run the FastAPI app
        shell: powershell
        run: |
          $envPath = "$env:USERPROFILE\actions-cache\env"
          & "$envPath\Scripts\Activate.ps1"
          Set-Location -Path Day10/workshop
          Start-Process -NoNewWindow -FilePath python -ArgumentList "app.py"

      - name: Wait and verify app running (optional)
        shell: powershell
        run: |
          Start-Sleep -Seconds 10
          Invoke-RestMethod -Uri http://localhost:5001/
