name: Train, Log and Deploy Model

on:
  push:
    branches: [Day10]

jobs:
  train-model:
    runs-on: IceCream

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Execution Policy
        run: Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope Process -Force
        shell: powershell

      - name: Create Python environment
        shell: powershell
        run: |
          $envPath = "$env:USERPROFILE\actions-cache\env"
          if (-not (Test-Path $envPath)) {
            python -m venv $envPath
          }

      - name: Train Model
        shell: powershell
        run: |
          $envPath = "$env:USERPROFILE\actions-cache\env"
          & "$envPath\Scripts\Activate.ps1"
          pip install --quiet pandas scikit-learn joblib
          Set-Location Day10/workshop
          python 1_train_model.py

      - name: Log and Register Model
        shell: powershell
        run: |
          $envPath = "$env:USERPROFILE\actions-cache\env"
          & "$envPath\Scripts\Activate.ps1"
          pip install --quiet mlflow scikit-learn joblib
          Set-Location Day10/workshop
          python 2_register_model.py

  dockerize-model:
    runs-on: IceCream
    needs: train-model

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t yourdockerhubusername/icecream-api:latest .

      - name: Push Docker image
        run: docker push yourdockerhubusername/icecream-api:latest
